### ISSUE TITLE
Users table

### ISSUE THREAD

**Issue by dat1010** [Adi-and-David/logic-land#6]
Django already comes with a Users table. I don't think we will need our users table and relationship to the world. If we use their users table then we can use predefined classes like login_required. See attachment for more details. Let's discuss this next Sunday.

![usersdb](https://cloud.githubusercontent.com/assets/2968756/12904491/dbad109a-ce9d-11e5-8274-f9ae59612007.png)

![loginrequiredexample](https://cloud.githubusercontent.com/assets/2968756/12904592/5e568382-ce9e-11e5-9d06-6e987a0e2607.png)

**Comment by thebugcatcher** [comment]
Yeah. I noticed that too. I wasn't sure if it'll allow us to add foreign keys to the user database though.

**Comment by thebugcatcher** [comment]
:+1:
